# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MongoDB
        run: |
          echo "[mongodb-org-4.4]" | sudo tee /etc/yum.repos.d/mongodb-org-4.4.repo
          echo "name=MongoDB Repository" | sudo tee -a /etc/yum.repos.d/mongodb-org-4.4.repo
          echo "baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/" | sudo tee -a /etc/yum.repos.d/mongodb-org-4.4.repo
          echo "gpgcheck=1" | sudo tee -a /etc/yum.repos.d/mongodb-org-4.4.repo
          echo "enabled=1" | sudo tee -a /etc/yum.repos.d/mongodb-org-4.4.repo
          echo "gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc" | sudo tee -a /etc/yum.repos.d/mongodb-org-4.4.repo
          sudo yum install -y mongodb-org
          sudo service mongod start

      - name: Wait for MongoDB to start
        run: sleep 15

      - name: Initialize MongoDB Databases and Collections
        run: |
          mongo --eval 'use ms_products; db.createCollection("products");'

          mongo --eval 'use ms_shopping; db.createCollection("carts");'
          mongo --eval 'use ms_shopping; db.createCollection("orders");'
          mongo --eval 'use ms_shopping; db.createCollection("shoppings");'
          mongo --eval 'use ms_shopping; db.createCollection("wishlists");'

          mongo --eval 'use ms_customers; db.createCollection("addresses");'
          mongo --eval 'use ms_customers; db.createCollection("customers");'

      - name: Test Customer Service
        working-directory: ./customer
        run: |
          npm ci
          npm test

      - name: Test Products Service
        working-directory: ./products
        run: |
          npm ci
          npm test

      - name: Test Shopping Service
        working-directory: ./shopping
        run: |
          npm ci
          npm test
