# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MongoDB Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Wait for MongoDB to start
        run: sleep 15

      - name: Initialize MongoDB Databases and Collections
        run: |
          mongo --eval 'use ms_products; db.createCollection("products");'

          mongo --eval 'use ms_shopping; db.createCollection("carts");'
          mongo --eval 'use ms_shopping; db.createCollection("orders");'
          mongo --eval 'use ms_shopping; db.createCollection("shoppings");'
          mongo --eval 'use ms_shopping; db.createCollection("wishlists");'

          mongo --eval 'use ms_customers; db.createCollection("addresses");'
          mongo --eval 'use ms_customers; db.createCollection("customers");'

      - name: Test Customer Service
        working-directory: ./customer
        run: |
          npm ci
          npm test

      - name: Test Products Service
        working-directory: ./products
        run: |
          npm ci
          npm test

      - name: Test Shopping Service
        working-directory: ./shopping
        run: |
          npm ci
          npm test
