# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create customer Test Env file
        working-directory: ./customer
        run: |
          touch .env.test
          echo MONGODB_URI=${{ secrets.TEST_CUSTOMER_DB_URL }} >> .env.test
          echo MSG_QUEUE_URL=${{ secrets.TEST_MSG_QUEUE_URL }} >> .env.test
          echo EXCHANGE_NAME=ONLINE_STORE >> .env.test
          cat .env.test

      - name: Test Customer Service
        working-directory: ./customer
        run: |
          npm ci
          npm test

      - name: Create products Test Env file
        working-directory: ./products
        run: |
          touch .env.test
          echo MONGODB_URI=${{ secrets.TEST_PRODUCTS_DB_URL }} >> .env.test
          echo MSG_QUEUE_URL=${{ secrets.TEST_MSG_QUEUE_URL }} >> .env.test
          echo EXCHANGE_NAME=ONLINE_STORE >> .env.test
          cat .env.test

      - name: Test Products Service
        working-directory: ./products
        run: |
          npm ci
          npm test

      - name: Create shopping Env file
        working-directory: ./shopping
        run: |
          touch .env.test
          echo MONGODB_URI=${{ secrets.TEST_SHOPPING_DB_URL }} >> .env.test
          echo MSG_QUEUE_URL=${{ secrets.TEST_MSG_QUEUE_URL }} >> .env.test
          echo EXCHANGE_NAME=ONLINE_STORE >> .env.test
          cat .env.test

      - name: Test Shopping Service
        working-directory: ./shopping
        run: |
          npm ci
          npm test